apiVersion: v1
kind: Service
metadata:
  name: metrics-siteconfig-open-cluster-management-io
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: siteconfig-metrics-server-cert
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: siteconfig-controller-manager
