apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: siteconfig-controller
    app.kubernetes.io/component: siteconfig
    control-plane: siteconfig-controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    workload.openshift.io/allowed: management
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siteconfig-controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: siteconfig-controller
    app.kubernetes.io/component: siteconfig
    control-plane: siteconfig-controller-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: siteconfig-controller
      app.kubernetes.io/component: siteconfig
      control-plane: siteconfig-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: siteconfig-controller
        app.kubernetes.io/component: siteconfig
        control-plane: siteconfig-controller-manager
      annotations:
        openshift.io/scc: restricted
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager      
        command:
        - /usr/local/bin/siteconfig-manager
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8443"
        - "--metrics-tls-cert-dir=/secrets/certs/metrics"
        - "--clusterinstance-webhook-tls-cert-dir=/secrets/certs/webhook-server"        
        - "--leader-elect"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: "1Gi"
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
          name: https
        volumeMounts:
        - mountPath: /secrets/certs/webhook-server
          name: webhook-certs
          readOnly: true
        - mountPath: /secrets/certs/metrics
          name: metrics-certs
          readOnly: true          
      serviceAccountName: siteconfig-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: webhook-certs
        secret:
          defaultMode: 420
          secretName: siteconfig-webhook-server-cert
      - name: metrics-certs
        secret:
          defaultMode: 420
          secretName: siteconfig-metrics-server-cert
