apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: siteconfig-controller
    app.kubernetes.io/component: siteconfig
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    workload.openshift.io/allowed: management
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: siteconfig-controller
    app.kubernetes.io/component: siteconfig
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: siteconfig-controller
      app.kubernetes.io/component: siteconfig
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: siteconfig-controller
        app.kubernetes.io/component: siteconfig
        control-plane: controller-manager
      annotations:
        openshift.io/scc: restricted
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /usr/local/bin/manager
        args:
        - --leader-elect
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: "1Gi"
          limits:
            cpu: "2"
            memory: 16Gi
            ephemeral-storage: 10Gi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
