apiVersion: v1
kind: Service
metadata:
  name: webhook-clusterinstances-siteconfig-open-cluster-management-io
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: siteconfig-webhook-server-cert  
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: siteconfig-controller-manager
