# permissions for end users to view clusterinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinstance-viewer-role
rules:
- apiGroups:
  - siteconfig.open-cluster-management.io
  resources:
  - clusterinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - siteconfig.open-cluster-management.io
  resources:
  - clusterinstances/status
  verbs:
  - get
