# permissions for end users to edit clusterinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinstance-editor-role
rules:
- apiGroups:
  - siteconfig.open-cluster-management.io
  resources:
  - clusterinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - siteconfig.open-cluster-management.io
  resources:
  - clusterinstances/status
  verbs:
  - get
