# permissions for end users to edit clusterinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterinstance-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: siteconfig
    app.kubernetes.io/part-of: siteconfig
    app.kubernetes.io/managed-by: kustomize
  name: clusterinstance-editor-role
rules:
- apiGroups:
  - siteconfig.open-cluster-management.io
  resources:
  - clusterinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - siteconfig.open-cluster-management.io
  resources:
  - clusterinstances/status
  verbs:
  - get
