apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: siteconfig.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterInstance is the Schema for the clusterinstances API
      displayName: Cluster Instance
      kind: ClusterInstance
      name: clusterinstances.siteconfig.open-cluster-management.io
      version: v1alpha1
  description: Manage SiteConfig
  displayName: siteconfig
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - a
  - v
  - x
  links:
  - name: Siteconfig
    url: https://siteconfig.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
