apiVersion: metaclusterinstall.openshift.io/v1alpha1
kind: SiteConfig
metadata:
  name: "site-sno-du-1"
  namespace: "site-sno-du-1"
spec:
  baseDomain: "example.com"
  pullSecretRef:
    name: "pullSecretName"
  sshPublicKey: "ssh-rsa "
  clusterName: "site-sno-du-1"
  proxy:
    noProxys: "foobar"
  caBundleRef:
    name: "my-bundle-ref"
  extraManifestsRefs:
    - name: foobar1
    - name: foobar2
  networkType: OVNKubernetes
  installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
  clusterLabels:
    group-du-sno: "test"
    common: "true"
    sites : "site-sno-du-1"
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.16.231.0/24
  serviceNetwork:
    - 172.30.0.0/16
  additionalNTPSources:
    - NTP.server1
    - 10.16.231.22
  ignitionConfigOverride: "igen"
  diskEncryption:
    type: "nbde"
    tang:
      - url: "http://10.0.0.1:7500"
        thumbprint: "1234567890"
  clusterType: SNO
  templateRefs:
    - name: aci-cluster-crs-v1
      namespace: siteconfig-system
  nodes:
    - hostName: "node1"
      role: "master"
      templateRefs:
        - name: aci-node-crs-v1
          namespace: siteconfig-system
      ironicInspect: ""
      bmcAddress: "idrac-virtualmedia+https://10.16.231.87/redfish/v1/Systems/System.Embedded.1"
      bmcCredentialsName:
        name: "name of bmcCredentials secret"
      bootMACAddress: "00:00:00:01:20:30"
      bootMode: "UEFI"
      rootDeviceHints:
        hctl: "1:2:0:0"
      cpuset: "2-19,22-39"
      installerArgs: '["--append-karg", "nameserver=8.8.8.8", "-n"]'
      ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/containers/registries.conf", "overwrite": true, "contents": {"source": "data:text/plain;base64,aGVsbG8gZnJvbSB6dHAgcG9saWN5IGdlbmVyYXRvcg=="}}]}}'
      nodeNetwork:
        interfaces:
          - name: eno1
            macAddress: "00:00:00:01:20:30"
          - name: eth0
            macAddress: "02:00:00:80:12:14"
          - name: eth1
            macAddress: "02:00:00:80:12:15"
        config:
          interfaces:
            - name: eno1
              type: ethernet
              ipv4:
                enabled: true
                dhcp: false
                address:
                  - ip: 10.16.231.3
                    prefix-length: 24
                  - ip: 10.16.231.28
                    prefix-length: 24
                  - ip: 10.16.231.31
                    prefix-length: 24
              ipv6:
                enabled: true
                dhcp: false
                address:
                  - ip: "2620:52:0:10e7:e42:a1ff:fe8a:601"
                    prefix-length: 64
                  - ip: "2620:52:0:10e7:e42:a1ff:fe8a:602"
                    prefix-length: 64
                  - ip: "2620:52:0:10e7:e42:a1ff:fe8a:603"
                    prefix-length: 64
            - name: bond99
              type: bond
              state: up
              ipv6:
                address:
                  - ip: "2620:52:0:1302::100"
                prefix-length: 64
                enabled: true
                link-aggregation:
                  mode: balance-rr
                  options:
                    miimon: '140'
                  slaves:
                    - eth0
                    - eth1
          dns-resolver:
            config:
              server:
                - 10.19.42.41
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.16.231.254
                next-hop-interface: eno1
                table-id: 254

