apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/siteconfig?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: siteconfig-main
    appstudio.openshift.io/component: siteconfig-main
    pipelines.appstudio.openshift.io/type: build
  name: siteconfig-main-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: hermetic
    value: 'true'
  - name: build-source-image
    value: 'true'
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-main/siteconfig-main:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/ppc64le
    - linux/s390x
    - linux/arm64
  - name: dockerfile
    value: build/Dockerfile.rhtap
  - name: path-context
    value: .
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-siteconfig-main
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
