// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stolostron/siteconfig/internal/controller/reinstall (interfaces: SpokeClientFactory)
//
// Generated by this command:
//
//	mockgen -destination=spoke_client_factory_mock_generated.go -package=mocks github.com/stolostron/siteconfig/internal/controller/reinstall SpokeClientFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockSpokeClientFactory is a mock of SpokeClientFactory interface.
type MockSpokeClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSpokeClientFactoryMockRecorder
	isgomock struct{}
}

// MockSpokeClientFactoryMockRecorder is the mock recorder for MockSpokeClientFactory.
type MockSpokeClientFactoryMockRecorder struct {
	mock *MockSpokeClientFactory
}

// NewMockSpokeClientFactory creates a new mock instance.
func NewMockSpokeClientFactory(ctrl *gomock.Controller) *MockSpokeClientFactory {
	mock := &MockSpokeClientFactory{ctrl: ctrl}
	mock.recorder = &MockSpokeClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpokeClientFactory) EXPECT() *MockSpokeClientFactoryMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockSpokeClientFactory) CreateClient(ctx context.Context, kubeconfigData []byte) (client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, kubeconfigData)
	ret0, _ := ret[0].(client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockSpokeClientFactoryMockRecorder) CreateClient(ctx, kubeconfigData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockSpokeClientFactory)(nil).CreateClient), ctx, kubeconfigData)
}
